fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(
                tauri_build::AppManifest::new()                .commands(&[
                    "get_native_features",
                    "get_port",
                    "app_close",
                    "oauth_loopback_start",
                ]),
            )
            .plugins([
                (
                    "web",
                    tauri_build::InlinedPlugin::new()
                        .commands(&["open_browser", "pubsub_broadcast", "config"])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "osc",
                    tauri_build::InlinedPlugin::new()
                        .commands(&["send"])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "audio",
                    tauri_build::InlinedPlugin::new()
                        .commands(&[
                            "play_async",
                            "list_input_devices",
                            "list_output_devices",
                            "start_audio_capture",
                            "stop_audio_capture",
                        ])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "windows-tts",
                    tauri_build::InlinedPlugin::new()
                        .commands(&["speak", "get_voices"])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "uberduck-tts",
                    tauri_build::InlinedPlugin::new()
                        .commands(&["speak", "get_voices"])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "keyboard",
                    tauri_build::InlinedPlugin::new()
                        .commands(&["start_tracking", "stop_tracking"])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "uwu",
                    tauri_build::InlinedPlugin::new()
                        .commands(&["translate"])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "whisper",
                    tauri_build::InlinedPlugin::new()
                        .commands(&[
                            "ensure_dependencies",
                            "start_recording",
                            "stop_recording",
                            "feed_audio_chunk",
                        ])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "translate",
                    tauri_build::InlinedPlugin::new()
                        .commands(&[
                            "set_endpoint",
                            "get_languages",
                            "translate",
                            "detect_language",
                            "check_availability",
                        ])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "kokoro-tts",
                    tauri_build::InlinedPlugin::new()
                        .commands(&[
                            "set_kokoro_endpoint",
                            "get_kokoro_voices",
                            "kokoro_speak",
                            "check_kokoro_availability",
                        ])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "moonshine-stt",
                    tauri_build::InlinedPlugin::new()
                        .commands(&[
                            "set_moonshine_endpoint",
                            "moonshine_transcribe",
                            "check_moonshine_availability",
                        ])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "melo-tts",
                    tauri_build::InlinedPlugin::new()
                        .commands(&[
                            "set_melo_endpoint",
                            "get_melo_speakers",
                            "melo_speak",
                            "check_melo_availability",
                        ])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "chatterbox-tts",
                    tauri_build::InlinedPlugin::new()
                        .commands(&[
                            "set_chatterbox_endpoint",
                            "get_chatterbox_voices",
                            "chatterbox_speak",
                            "check_chatterbox_availability",
                        ])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "fish-speech",
                    tauri_build::InlinedPlugin::new()
                        .commands(&[
                            "set_fish_endpoint",
                            "get_fish_voices",
                            "fish_speak",
                            "check_fish_availability",
                        ])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "voice-changer",
                    tauri_build::InlinedPlugin::new()
                        .commands(&[
                            "get_voice_changer_presets",
                            "get_voice_changer_params",
                            "set_voice_changer_params",
                            "set_voice_changer_enabled",
                            "apply_voice_changer_preset",
                            "start_voice_changer",
                            "stop_voice_changer",
                            "is_voice_changer_running",
                        ])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
                (
                    "vosk-stt",
                    tauri_build::InlinedPlugin::new()
                        .commands(&[
                            "get_vosk_models",
                            "check_vosk_native_availability",
                            "set_vosk_model_path",
                            "get_vosk_model_path",
                            "vosk_native_transcribe",
                            "download_vosk_model",
                            "list_downloaded_vosk_models",
                        ])
                        .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
                ),
            ]),
    )
    .expect("failed to run tauri-build");
}
